### ISSUE TITLE
RFC 1001: make instance name mandatory

### ISSUE THREAD

**Issue by tailhook** [edgedb/rfcs#20]
Since we now want to recommend creating named edgedb instances:
```
edgedb server init <instance_name>
```
I propose the following changes to RFC:
1. Make `instance-name` mandatory argument for: `init`/`start`/`stop`/`restart`/`reset-password`
2. Make `edgedb server status` == `edgedb server status --all` (see all instances instead of default if nothing specified)
3. Get rid of quirk of mapping `default` to 5656, `default` may be used as ordinary name

**Comment by 1st1** [comment]
Might be related https://github.com/edgedb/edgedb/discussions/1781

**Comment by elprans** [comment]
This makes sense, since we're now gravitating toward recommending to use instances per project (to simplify upgrades, maintentance etc).
