### ISSUE TITLE
RFC 1005 does not respect XDG Base Directory Specification

### ISSUE THREAD

**Issue by Fogapod** [edgedb/rfcs#32]
XDG Base Directory Specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html

`~/.edgedb/projects` folder structure is mentioned multiple times in RFC 1005: https://github.com/edgedb/rfcs/blob/master/text/1005-edgedb-project.rst

This is an inconvenience for me and many other Linux desktop users, there are too many apps that think they're special and should have a folder in home directory.

`~/.edgedb` should be a last resort folder in case `$XDG_CONFIG_HOME` is not defined.

This should be relatively easy to implement: checking additional set of env variables before writing/reading config files. I suggest making changes to RFC and implementations before 1.0.

related: https://github.com/edgedb/edgedb-cli/issues/308

**Comment by elprans** [comment]
We've switched to XDG-conforming layout on Linux in Beta 3: https://www.edgedb.com/blog/edgedb-beta-3-ross#if-you-have-an-older-version-installed
